

CREATE TABLE SIRENE (
code_entreprise TEXT,
code_etablissement TEXT,
departement TEXT,
code insee TEXT,    --DEPET || COMET
DEPET TEXT,
COMET TEXT,
NIC TEXT,
enseigne TEXT,
nom_etablissement TEXT,
code_naf TEXT 
);

ALTER TABLE SIRENE ADD COLUMN CODE_INSEE TEXT;
UPDATE SIRENE SET CODE_INSEE = DEPET || COMET WHERE DEPET IS NOT NULL AND COMET IS NOT NULL;
CREATE INDEX code_insee_idx ON SIRENE(CODE_INSEE);
CREATE INDEX departement_idx ON SIRENE(departement);

